### ISSUE TITLE
USB / JTAG subsystem

### ISSUE THREAD

**Issue by kaolpr** [elhep/MicroTCA-chassis#6]
To make product more versatile, I'd like to suggest the following USB / JTAG subsystem:

![mtca_chassis_jtag](https://user-images.githubusercontent.com/9166701/145452082-9a532d7a-f410-4054-982a-1a78653dddf4.png)

- We would always have an entry-point with UART to the MCU.
- Additionally, if one wants to use USB JTAG, a Digilent programming module can be used ([link](https://digilent.com/shop/jtag-smt2-nc-surface-mount-programming-module/)) as an assembly option with FT2232, if no Xilinx Vivado compatibility is required. 
- Above path could be used in one of two ways: driven from external USB port or from the MCU (with SW mux driven by MCU). When driven from the MCU one could use USB over IP for remote debugging if, for some reason, remote debugging with XVC is not working or target is not Xilinx device.
- There is also option for plugging JTAG adapter directly. In such case BUFs are disabled.
- Onboard USB Host connector is foreseen for remote use of some debug adapter that is not in AMC chain (e.g. MMC). This connector would be on the main board, not exposed to the front panel.

Approximate costs:
- JTAG SMT2-NC: 49 USD
- FT2232: 4.25 USD
- USB-UART: 2.5 USD
- USB-HUB: 3.5 USD
- BUF: 4*0.8 USD = 3.2 USD
- SW: 0.44 USD

**Total:** 21.64 USD (FT2232) or 66.40 USD (SMT2-NC) + logistics + manufacturing

**Comment by gkasprow** [comment]
can't we just use JTAG over SPI?

**Comment by gkasprow** [comment]
can't single FT2232 be used as both UART and JTAG ?

**Comment by gkasprow** [comment]
what about using a switch that connects FT2232 either to SBC to external micro USB (device). We could have two use cases:
1. UART + JTAG operated locally (USB plugged)
2. JTAG operated remotely (USB unplugged)
 I don't know if we need more scenarios

**Comment by gkasprow** [comment]
actually, we can run Xilinx VCS over GPIO. 
https://github.com/kholia/xvcpi

**Comment by gkasprow** [comment]
btw, FT2232 is unobtanium these days..

**Comment by gkasprow** [comment]
I would keep it simple:
- use Cypress USB bridge as a serial terminal
- use JTAG header inside followed by the mux
- connect SBC IO to the mux and run XVCS
- use USB host connector inside
- when one wants to use a more sophisticated JTAG, one inserts Xilinx/Altera cable it into the USB host and JTAG header

In this way, we have all scenarios as primarily mentioned at a fraction of cost.

**Comment by gkasprow** [comment]
not all AMCs implement JTAG over AMC connectors. in this way we would connect the programmer between the SBC host and native JTAG connector

**Comment by kaolpr** [comment]
![mtca_chassis_jtag](https://user-images.githubusercontent.com/9166701/145983469-16c4ab80-fe2c-4af5-9c42-97fc26670536.png)

I appreciate simplicity. However, I'd opt for a minor additions:

* assembly variant for on-board FT2232 / JTAG-SMT2-NC, it's sort of appealing to have Xilinx debugging onboard without any additional elements,
* 2 onboard USB host connectors,
* 3 port USB 2.0 hub for serving onboard USB connectors and optional FT2232.

**Comment by gkasprow** [comment]
Actually, we don't necessarily need a USB hub, we can use a switch instead. It's hard to buy any switch these days

**Comment by gkasprow** [comment]
That's not that bad, some hubs are still available, i.e. USB2503-HZH, USB2504A-JT

**Comment by kaolpr** [comment]
Actually, there is even some choice: [LINK](https://pl.mouser.com/c/semiconductors/interface-ics/usb-interface-ic/?q=usb%20hub&product=USB%20Hubs&standard=USB%202.0&instock=y&sort=pricing)

**Comment by gkasprow** [comment]
yep, a few months ago it was much worse :)

**Comment by gkasprow** [comment]
wow, even some UART bridges are again available ;D

**Comment by gkasprow** [comment]
I used Atmega32U4 as a USB to master/slave I2C bridge due to FTDI issues
